// Escribe un programa que pida al usuario
// ingresar un número, luego pide un segundo
// número e imprime en la consola la suma de
// los dos números ingresados.

const numero1 = prompt("ingrese un numero del 1 a 100");
const numero2 = prompt("ingrseo igualmente un nuemro del 1 a el 100");;

const 
    numero = Number(numero1)
    numero0 = Number(numero2)

const total = numero + numero0;

console.log( `la suma de ${numero1} y ${numero2} es: ${total}` );